site_name: "CMU 17-313: Foundations of Software Engineering"

theme:
  name: material
  custom_dir: overrides
  logo: assets/images/17313_numberbox.png
  favicon: assets/favicon.ico
  font:
    text: Roboto
  palette:
    - scheme: default
      primary: red
      accent: red
      toggle:
          icon: material/brightness-7
          name: Switch to dark mode
    - scheme: slate
      primary: red
      accent: red
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.top
    - navigation.tracking

markdown_extensions:
  - attr_list
  - admonition
  - md_in_html
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.superfences
  - tables
  - toc:
      title: On This Page
      toc_depth: 4

extra_css:
  - stylesheets/custom.css

plugins:
  - search
  - markdownextradata

nav:
  - Home: index.md
  - Course Overview: overview.md
  - Syllabus: syllabus.md
  - Assignments: assignments/index.md # Dummy home page; remove once we start adding assignments below
    # - Homework 1: assignments/HW1.md
    # - Homework 2: assignments/HW2.md
    # - Homework 3: assignments/HW3.md
    # - Homework 4: assignments/HW4.md
    # - Homework 5: assignments/HW5.md
    # - Homework 6: assignments/HW6.md
  - Recitations: recitations/index.md # Dummy home page; remove once we start adding recitations below
    # - Recitation 1: recitations/reci1-github.md
    # - Recitation 2: recitations/reci2-angularjs.md
    # - Recitation 3: recitations/reci3-archaeology.md
    # - Recitation 4: recitations/reci4-dysfunction.md
    # - Recitation 6: recitations/reci6-midterm-review.md
    # - Recitation 7: recitations/reci7-machine-learning.md
    # - Recitation 8: recitations/reci8-static-analysis-ci.md
    # - Recitation 9: recitations/reci9-open-source.md